---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  GH_OAUTH_URL:   https://github.com/login/oauth/authorize
  GH_TOKEN_URL:   https://github.com/login/oauth/access_token
  GH_SCOPE:       email

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292

production:
  API_URL: https://edocuments-api.herokuapp.com/api/v1
  APP_URL: https://edocuments-app.herokuapp.com
  REDIS_URL: redis://h:p00005dee83135381aad3115361d5debec2cb8c6cb283952099831d93e1e4ecf0@ec2-54-174-89-111.compute-1.amazonaws.com:7969
