# Use as template for secrets.yml
---
development:
  SESSION_SECRET:   "TS1un/H/itoZyv9KhVvPTnJcidM6HNxy9+PSJSlIeJWZfFzf+XCMgWtwhLgUn751JkSBx+KbkkyXMh9T9WbeXQ=="
  MSG_KEY:          OokU7DuD7bMcb0Lh4HEhdCKJkhdu/YJzMUyPIlyMni0=
  REDIS_URL:        "redis://h:p90219c2145cf8e08d439fdee8c3afd12aac69bf1300107c65d0c01fc3acaa07e@ec2-34-229-2-207.compute-1.amazonaws.com:10479"
  GH_CLIENT_ID:     "7b4362ae9216d6b0603d"
  GH_CLIENT_SECRET: "e37f06c0ef9366eed1bf2e2d208fedb16d2d982d"
  SIGNING_KEY: +mpEu13fFOETM03FlQSzvCn/Ci1JsywUT/mK2XPYYcE=

test:
  SESSION_SECRET: "/JZWSs/qYjIyh0YCK3ocCtKGnBmms+ngwK7tlN1f3q5JqC6Uzo+3GcZ8+ADuibcSmCVxQZF8mNdiVB3hOsIA6w=="
  MSG_KEY:        'TPSzL6hmx0z1ZVSm+F+gPSAYqW1Gh690d1HLetkoOhk='
  REDIS_URL:      "redis://rediscloud:password@localhost:6379"
  GH_CLIENT_ID:     <Get Github OAuth Client ID>
  GH_CLIENT_SECRET: <Get Github OAuth Client Secret>

production:
  SESSION_SECRET: "<generate: `rake generate:session_secret`; add to production envirnoment variables>"
  MSG_KEY:        "<generate: `rake generate:msg_key`; add to production envirnoment variables>"
  REDIS_URL:      "redis://rediscloud:password@localhost:6379"
  GH_CLIENT_ID:     <Get Github OAuth Client ID>
  GH_CLIENT_SECRET: <Get Github OAuth Client Secret>