---
development:
  SESSION_SECRET: "RBZoyfiqVagw3yc5+D7xiqg5RbSkBTPT7xuGRLBEWzGq8eQ/9KlVSOCZwVALlboUp2DJ9EBjb7UtDIKGSCExvA=="
  MSG_KEY:       '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  REDIS_URL:      "redis://h:p00005dee83135381aad3115361d5debec2cb8c6cb283952099831d93e1e4ecf0@ec2-54-174-89-111.compute-1.amazonaws.com:7969"
  SIGNING_KEY:    EL9j1WuNH9LdmKc2omVcou02Tkyldt/25wRi6LLcODA=

test:
  SESSION_SECRET: "RBZoyfiqVagw3yc5+D7xiqg5RbSkBTPT7xuGRLBEWzGq8eQ/9KlVSOCZwVALlboUp2DJ9EBjb7UtDIKGSCExvA=="
  MSG_KEY:        "aT0rR0FYcIvXsu4XyL/HVTkK5ayvoeHGGYh0lDrIkFY="
  REDIS_URL:      "redis://h:p00005dee83135381aad3115361d5debec2cb8c6cb283952099831d93e1e4ecf0@ec2-54-174-89-111.compute-1.amazonaws.com:7969"

production:
  SESSION_SECRET: "RBZoyfiqVagw3yc5+D7xiqg5RbSkBTPT7xuGRLBEWzGq8eQ/9KlVSOCZwVALlboUp2DJ9EBjb7UtDIKGSCExvA=="
  MSG_KEY:        "aT0rR0FYcIvXsu4XyL/HVTkK5ayvoeHGGYh0lDrIkFY="
  REDIS_URL:      "redis://h:p00005dee83135381aad3115361d5debec2cb8c6cb283952099831d93e1e4ecf0@ec2-54-174-89-111.compute-1.amazonaws.com:7969"